name: barcode_input_listener
description: "A Flutter package for listening to barcode inputs"
version: 0.0.2
homepage: https://github.com/Umer8627/barcode-input-listener
environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
